/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PersonaService;
import javax.swing.JOptionPane;

/**
 *
 * @author PCLino
 */
public class GestionPersonal extends javax.swing.JFrame {

    /**
     * Creates new form GestionPersonal
     */
    private PersonaService personaService;
    public GestionPersonal(PersonaService personaService) {
    this.personaService = personaService;
    initComponents(); 
    labelregistro.setVisible(false);
    btnregistrar.setVisible(false);
    dni1txt.setVisible(false);
    }


    /**
     *
     * @param personaService
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelpersonas = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        labelregistro = new javax.swing.JLabel();
        btnregistrar = new javax.swing.JButton();
        dni1txt = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menubar = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelpersonas.setBackground(new java.awt.Color(51, 153, 255));

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelregistro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelregistro.setForeground(new java.awt.Color(0, 0, 0));
        labelregistro.setText("REGISTRO DE DNI:");

        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelpersonasLayout = new javax.swing.GroupLayout(panelpersonas);
        panelpersonas.setLayout(panelpersonasLayout);
        panelpersonasLayout.setHorizontalGroup(
            panelpersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpersonasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelpersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpersonasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23))
                    .addGroup(panelpersonasLayout.createSequentialGroup()
                        .addGroup(panelpersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnregistrar)
                            .addGroup(panelpersonasLayout.createSequentialGroup()
                                .addComponent(labelregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dni1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(123, Short.MAX_VALUE))))
        );
        panelpersonasLayout.setVerticalGroup(
            panelpersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpersonasLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(panelpersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelregistro)
                    .addComponent(dni1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnregistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        menubar.setText("Añadir");
        menubar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menubarMenuSelected(evt);
            }
        });
        menubar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menubarMouseClicked(evt);
            }
        });
        menubar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubarActionPerformed(evt);
            }
        });
        jMenuBar1.add(menubar);

        jMenu2.setText("Modificar");
        jMenuBar1.add(jMenu2);

        jMenu1.setText("Eliminar");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Listar");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelpersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelpersonas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        dispose();   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menubarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubarActionPerformed
       
    }//GEN-LAST:event_menubarActionPerformed

    private void menubarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubarMouseClicked
        labelregistro.setVisible(true);
        btnregistrar.setVisible(true);
        dni1txt.setVisible(true);
    }//GEN-LAST:event_menubarMouseClicked

    private void menubarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menubarMenuSelected
      
    }//GEN-LAST:event_menubarMenuSelected

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        String dni = dni1txt.getText();

    boolean registrado = personaService.exitePersona(dni);

    if (registrado) {
        JOptionPane.showMessageDialog(this, "La persona puede ser registrada en la base");
    } else {
        JOptionPane.showMessageDialog(this, "La persona ya está registrada con ese DNI.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_btnregistrarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistrar;
    private javax.swing.JTextField dni1txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelregistro;
    private javax.swing.JMenu menubar;
    private javax.swing.JPanel panelpersonas;
    // End of variables declaration//GEN-END:variables
}
