/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PersonaService;
import javax.swing.JOptionPane;

/**
 *
 * @author PCLino
 */
public class GestionPersonal extends javax.swing.JFrame {

    /**
     * Creates new form GestionPersonal
     */
    private PersonaService personaService;
    public GestionPersonal(PersonaService personaService) {
    this.personaService = personaService;
    initComponents(); 
    labelregistro.setVisible(false);
    btnañadir.setVisible(false);
    dni1txt.setVisible(false);
    btneliminar.setVisible(false);
    }


    /**
     *
     * @param personaService
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelpersonas = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        labelregistro = new javax.swing.JLabel();
        btnañadir = new javax.swing.JButton();
        dni1txt = new javax.swing.JTextField();
        btneliminar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menubar = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelpersonas.setBackground(new java.awt.Color(51, 153, 255));

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelregistro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelregistro.setForeground(new java.awt.Color(0, 0, 0));
        labelregistro.setText("Introduce DNI:");

        btnañadir.setText("Añadir");
        btnañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnañadirActionPerformed(evt);
            }
        });

        dni1txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dni1txtActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelpersonasLayout = new javax.swing.GroupLayout(panelpersonas);
        panelpersonas.setLayout(panelpersonasLayout);
        panelpersonasLayout.setHorizontalGroup(
            panelpersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpersonasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
            .addGroup(panelpersonasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelpersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnañadir)
                    .addGroup(panelpersonasLayout.createSequentialGroup()
                        .addComponent(labelregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(dni1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneliminar)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelpersonasLayout.setVerticalGroup(
            panelpersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpersonasLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(panelpersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelregistro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelpersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dni1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btneliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnañadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        menubar.setText("Añadir");
        menubar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menubarMenuSelected(evt);
            }
        });
        menubar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menubarMouseClicked(evt);
            }
        });
        menubar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubarActionPerformed(evt);
            }
        });
        jMenuBar1.add(menubar);

        jMenu2.setText("Modificar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu1.setText("Eliminar");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Listar");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelpersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelpersonas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        dispose();   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnañadirActionPerformed
    String dni = dni1txt.getText();

    boolean registrado = personaService.exitePersona(dni);

    if (registrado) {
        JOptionPane.showMessageDialog(this, "La persona puede ser registrada en la base");
        FormularioPersona registro = new FormularioPersona(dni1txt.getText(),personaService);
        dispose();
        registro.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "La persona ya está registrada con ese DNI.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_btnañadirActionPerformed

    private void dni1txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dni1txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dni1txtActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        
        Modificar modificar = new Modificar(personaService);
        modificar.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void menubarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubarActionPerformed

    }//GEN-LAST:event_menubarActionPerformed

    private void menubarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubarMouseClicked
        labelregistro.setVisible(true);
        btnañadir.setVisible(true);
        btneliminar.setVisible(false);
        dni1txt.setVisible(true);
    }//GEN-LAST:event_menubarMouseClicked

    private void menubarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menubarMenuSelected

    }//GEN-LAST:event_menubarMenuSelected

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        labelregistro.setVisible(true);
        btneliminar.setVisible(true);
        btnañadir.setVisible(false);
        dni1txt.setVisible(true);
    }//GEN-LAST:event_jMenu1MenuSelected

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
    String dni = dni1txt.getText();
    
    boolean registrado = personaService.exitePersona(dni);

    if (registrado) {
         JOptionPane.showMessageDialog(this, "No existe ese dni en la base", "Error", JOptionPane.ERROR_MESSAGE);
       
    } else {
        personaService.eliminarPersona(dni);
        JOptionPane.showMessageDialog(this, "La persona ha sido eliminada con exito");
    }
    dni1txt.setText("");
        
    }//GEN-LAST:event_btneliminarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnañadir;
    private javax.swing.JButton btneliminar;
    private javax.swing.JTextField dni1txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelregistro;
    private javax.swing.JMenu menubar;
    private javax.swing.JPanel panelpersonas;
    // End of variables declaration//GEN-END:variables
}
