/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PersonaService;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Directivo;
import modelo.Jugador;
import modelo.Persona;
import modelo.Tecnico;

/**
 *
 * @author PCLino
 */
public class Modificar extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    private final PersonaService personaService;
    private List<Persona> personas;
    public Modificar(PersonaService personaService) {
        this.personaService = personaService;
        initComponents();
        cargarEnCombo();

    }
    
    private void cargarEnCombo() {
    cbtipo.removeAllItems();
    personas = personaService.listarActivos();

    for (Persona persona : personas) {
        cbtipo.addItem(persona.getNombrecompleto());  // Solo metemos el nombre al Combo
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnmodficar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbtipo = new javax.swing.JComboBox<>();
        lblnombre = new javax.swing.JLabel();
        nombretxt = new javax.swing.JTextField();
        lbltelefono = new javax.swing.JLabel();
        telefonotxt = new javax.swing.JTextField();
        labeldni = new javax.swing.JLabel();
        spnedad = new javax.swing.JSpinner();
        lblcargo = new javax.swing.JLabel();
        lblmercado = new javax.swing.JLabel();
        lblfisico = new javax.swing.JLabel();
        txtcargo = new javax.swing.JTextField();
        cbestado = new javax.swing.JComboBox<>();
        lblpuesto = new javax.swing.JLabel();
        lblespecialidad = new javax.swing.JLabel();
        txtespecialidad = new javax.swing.JTextField();
        txtpuesto = new javax.swing.JTextField();
        lbedad = new javax.swing.JLabel();
        spnvalormercado = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Modificar Persona");

        btnmodficar.setText("Modidficar");
        btnmodficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodficarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seleccione Persona:");

        cbtipo.setLightWeightPopupEnabled(false);
        cbtipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbtipoItemStateChanged(evt);
            }
        });

        lblnombre.setForeground(new java.awt.Color(0, 0, 0));
        lblnombre.setText("Nombre completo:");
        lblnombre.setEnabled(false);

        nombretxt.setEnabled(false);

        lbltelefono.setForeground(new java.awt.Color(0, 0, 0));
        lbltelefono.setText("Telefono:");
        lbltelefono.setEnabled(false);

        telefonotxt.setEnabled(false);
        telefonotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonotxtActionPerformed(evt);
            }
        });

        labeldni.setForeground(new java.awt.Color(0, 0, 0));

        spnedad.setEnabled(false);

        lblcargo.setForeground(new java.awt.Color(0, 0, 0));
        lblcargo.setText("Cargo:");
        lblcargo.setEnabled(false);

        lblmercado.setForeground(new java.awt.Color(0, 0, 0));
        lblmercado.setText("Valor mercado:");
        lblmercado.setEnabled(false);

        lblfisico.setForeground(new java.awt.Color(0, 0, 0));
        lblfisico.setText("Estado fisico:");
        lblfisico.setEnabled(false);

        txtcargo.setEnabled(false);

        cbestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Activo", "Lesionado", " " }));
        cbestado.setEnabled(false);
        cbestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbestadoActionPerformed(evt);
            }
        });

        lblpuesto.setForeground(new java.awt.Color(0, 0, 0));
        lblpuesto.setText("Puesto:");
        lblpuesto.setEnabled(false);

        lblespecialidad.setForeground(new java.awt.Color(0, 0, 0));
        lblespecialidad.setText("Especialidad");
        lblespecialidad.setEnabled(false);

        txtespecialidad.setEnabled(false);
        txtespecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtespecialidadActionPerformed(evt);
            }
        });

        txtpuesto.setEnabled(false);

        lbedad.setForeground(new java.awt.Color(0, 0, 0));
        lbedad.setText("Edad:");
        lbedad.setEnabled(false);

        spnvalormercado.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labeldni, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnmodficar)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbltelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(telefonotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbedad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(spnedad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblnombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblmercado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblfisico, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spnvalormercado)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtespecialidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(txtcargo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbestado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpuesto, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnvalormercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmercado))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblfisico, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblpuesto)
                            .addComponent(txtpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblcargo)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(lbltelefono)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spnedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbedad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblnombre))
                                .addGap(18, 18, 18)
                                .addComponent(telefonotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblespecialidad)
                    .addComponent(txtespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labeldni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodficar))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodficarActionPerformed
          String nombreSeleccionado = (String) cbtipo.getSelectedItem();

        for (Persona persona : personas) {
        if (persona.getNombrecompleto().equals(nombreSeleccionado)) {

            // Modificamos campos comunes
            persona.setNombrecompleto(nombretxt.getText());
            persona.setTelefono(Integer.parseInt(telefonotxt.getText()));

            // Si es Jugador
            if (persona instanceof Jugador jugador) {
                jugador.setEdad(Integer.parseInt(spnedad.getValue().toString()));
                jugador.setEstadofisico(cbestado.getSelectedItem().toString().equals("Activo"));
                jugador.setValormercado(Integer.parseInt(spnvalormercado.getValue().toString()));
            }

            // Si es Técnico
            else if (persona instanceof Tecnico tecnico) {
                tecnico.setEspecialidad(txtespecialidad.getText());
                tecnico.setPuesto(txtpuesto.getText());
            }

            // Si es Directivo
            else if (persona instanceof Directivo directivo) {
                directivo.setCargo(txtcargo.getText());
            }

            // Guardar en el repositorio
            personaService.actualizarPersona(persona);

            JOptionPane.showMessageDialog(this, "Cambios guardados correctamente.");
            dispose();
            break;
        }
        }
    }//GEN-LAST:event_btnmodficarActionPerformed

    private void cbestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbestadoActionPerformed

    private void txtespecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtespecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtespecialidadActionPerformed

    private void telefonotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonotxtActionPerformed

    private void cbtipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbtipoItemStateChanged
       lblnombre.setEnabled(true);
       nombretxt.setEnabled(true);
       telefonotxt.setEnabled(true);
       lbltelefono.setEnabled(true);
       if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        String nombreSeleccionado = (String) cbtipo.getSelectedItem();

        for (Persona persona : personas) {
            if (persona.getNombrecompleto().equals(nombreSeleccionado)) {
                // Ahora habilita según tipo
                if (persona instanceof Jugador) {
                    spnedad.setEnabled(true);
                    lbedad.setEnabled(true);
                    cbestado.setEnabled(true);
                    lblmercado.setEnabled(true);
                    lblfisico.setEnabled(true);
                    spnvalormercado.setEnabled(true);
                } else if (persona instanceof Tecnico) {
                    txtespecialidad.setEnabled(true);
                    lblespecialidad.setEnabled(true);
                    txtpuesto.setEnabled(true);
                    lblpuesto.setEnabled(true);
                } else if (persona instanceof Directivo) {
                   txtcargo.setEnabled(true);
                   lblcargo.setEnabled(true);
                }
                break;
            }
        }
    }
    }//GEN-LAST:event_cbtipoItemStateChanged

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmodficar;
    private javax.swing.JComboBox<String> cbestado;
    private javax.swing.JComboBox<String> cbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labeldni;
    private javax.swing.JLabel lbedad;
    private javax.swing.JLabel lblcargo;
    private javax.swing.JLabel lblespecialidad;
    private javax.swing.JLabel lblfisico;
    private javax.swing.JLabel lblmercado;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblpuesto;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JSpinner spnedad;
    private javax.swing.JSpinner spnvalormercado;
    private javax.swing.JTextField telefonotxt;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtespecialidad;
    private javax.swing.JTextField txtpuesto;
    // End of variables declaration//GEN-END:variables
}
